#!/usr/bin/env python3
import numpy as np
def non_lin(value, deriv_of_sigmoid=False):
    if deriv_of_sigmoid:
        return x * (1 - value)
    else:
        #find spot on sigmoid function https://en.wikipedia.org/wiki/Sigmoid_function
        #converts any value between 0 & 1, is our probability
        return 1/(1+np.exp(-value))

input_values = np.arra
