#!/usr/bin/env python3
import random
from time import sleep
import alphabeta as ab
import gamestate as gs
def get_p_move(game):
    while True:
        raw_move = input('Your move (1-9) > ')
        if raw_move.isdigit():
            p_move = int(raw_move) - 1
            if p_move in game.get_possible_moves():
                break
    return p_move

def run_game(game, player_goes_first):
    if player_goes_first:
        while True:
            game.pretty_print()
            p_move = get_p_move(game)
            game = game.get_next_state(p_move, False)
            if game.is_gameover(): break
            score, ai_move = ab.alphabeta(game)
            game = game.get_next_state(ai_move, True)
            if game.is_gameover(): break
    else:
        while True:
            score, ai_move = ab.alphabeta(game)
            game = game.get_next_state(ai_move, True)
            if game.is_gameover(): break
            game.pretty_print()
            p_move = get_p_move(game)
            game = game.get_next_state(p_move, False)
            if game.is_gameover(): break
    game.pretty_print()
    print('The computer ' + game.return_state(score))

def get_symbols():
    human_char = input('Pick your symbol > ')
    if len(human_char) > 1 or human_char == '' or human_char == ' ' or human_char == '_':
        exit()
    elif human_char == 'X' or human_char == 'x':
        ai_char = 'O'
    else:
        ai_char = 'X'
    return human_char, ai_char
if __name__ == '__main__':
    try:
        human_char, ai_char = get_symbols()
        start_board = ['_'] * 9
        player_goes_first = bool(random.randint(0,2))
            
        input('You go first:{}\nenter to continue\n'.format(player_goes_first))
        game = gs.GameState(start_board,char=ai_char, oppchar=human_char)
        run_game(game, player_goes_first)
    except KeyboardInterrupt:
        print('\n')
        exit()
